### ISSUE TITLE
Write Flywheel Subsystem

### ISSUE THREAD

**Issue by Inspirol** [Choate-Robotics/7407-DriveCode-Crescendo#7]

**Comment by mbardoe** [comment]
Let's look at how the shooter worked in 2022 to think about how we want to write the shooter subsystem and supporting programs. Take a look at this point in the code: [bodhi before turret](https://github.com/Choate-Robotics/7407-DriveCode-RapidReact/tree/94cfb9f4a1dbe9dd08fce3363232a6845414c799). Then we can start to write the basic commands that we want, and we can see how they used a ShooterTargeting class to handle the more complex stuff.
