### ISSUE TITLE
Create targetting formula

### ISSUE THREAD

**Issue by Inspirol** [Choate-Robotics/7407-DriveCode-Crescendo#8]

**Comment by mbardoe** [comment]
We have created a formula that can calculate the correct angle, disregarding air resistance. We would need to know the horizontal distance to the target and the vertical distance to the target. 

We are closing in on an iterative algorithm that calculates the angle, including air resistance, but then we would have to estimate the drag coefficient for the NOTE. We looked at several different possible drag coefficients, and based on an initial velocity of 15 m/s, the air resistance could cause the note to land up to 17 cm (6 in) lower than expected. Increasing the initial velocity to 20 m/s decreases the error to about  9 cm (3 in).

**Comment by Inspirol** [comment]
I am going to link the feat/shooter branch to this issue. Keeping the calculations in a Util file (maybe like shooter_calculations.py) and keeping the flywheels and wrist separate may be beneficial. The reason being we can spool up the flywheels independent of its aim and note indexing. That means we can start the flywheels before indexing a note (since to index a note, we need to aim way up to grab from the intake), keeping our auto and cycle times high. 

What do you guys think? This is just my opinion

**Comment by Inspirol** [comment]
https://www.chiefdelphi.com/t/frc-95-the-grasshoppers-2024-build-thread/442176/56

Grasshoppers show their top bottom and left right shooting statistics
